### ISSUE TITLE
new tag v0.0.7

### ISSUE THREAD

**Issue by ljurk** [metricq/grafana-metricq-datasource#10]
Hi,
could you create a new tag for the current master v0.0.7? For our grafana deployment we want to pin the version we want to install, currently we have to install from `https://github.com/metricq/grafana-metricq-datasource/archive/refs/heads/master.tar.gz` because v0.0.6 is still using angular, which already was fixed in #4

**Comment by bmario** [comment]
Fixed: https://github.com/metricq/grafana-metricq-datasource/releases/tag/v0.0.7
